name: build RPMs

on: [pull_request, push, release, workflow_dispatch]

jobs:
    photon-rpms:
        env:
            DIST: photon
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build container
              working-directory: ${{ github.workspace }}
              run: |
                cd ci/${DIST} && docker build -t ${DIST}-builder -f Dockerfile .
            - name: build rpms in container
              working-directory: ${{ github.workspace }}
              run: |
                docker run --rm -v $(pwd):/workdir -w /workdir ${DIST}-builder ./ci/${DIST}/build-rpms.sh
            - name: upload RPMs
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.DIST }}-rpms
                  path: rpmbuild/RPMS/
            - name: upload as release artifacts
              if: github.event_name == 'release'
              env:
                  GH_TOKEN: ${{ github.token }}
              run: gh release upload ${{ github.event.release.tag_name }} rpmbuild/RPMS/*/*.rpm